const apiNames = [
  'YouTube Data API v3',
  'Weather API',
  'Time Zone API',
  'Street View Static API',
  'Street View Publish API',
  'Solar API',
  'Service Usage API',
  'Service Management API',
  'Sensitive Data Protection (DLP)',
  'Routes API',
  'Route Optimization API',
  'Roads API',
  'Recommender API',
  'Pollen API',
  'Places UI Kit',
  'Places API (New)',
  'Places API',
  'Places Aggregate API',
  'People API',
  'Call Log API',
  'Phone API',
  'Navigation SDK',
  'Maps Static API',
  'Maps SDK for iOS',
  'Maps SDK for Android',
  'Maps Platform Datasets API',
  'Maps JavaScript API',
  'Maps Grounding API',
  'Maps Elevation API',
  'Maps Embed API',
  'Maps 3D SDK for iOS',
  'Maps 3D SDK for Android',
  'Map Tiles API',
  'Groups Settings API',
  'Google Workspace Reseller API',
  'Google Workspace Marketplace SDK',
  'Google Workspace Alert Center API',
  'Google Workspace add-ons API',
  'Google Tasks API',
  'Google Slides API',
  'Google Sheets API',
  'Google Maps for Fleet Routing',
  'Google Drive API',
  'Google Docs API',
  'Google Cloud Storage JSON API',
  'Google Cloud APIs',
  'Google Chat API',
  'Google Calendar API',
  'Gmail API',
  'Geolocation API',
  'Geocoding API',
  'Gemini for Google Cloud API',
  'Fitness API',
  'Enterprise License Manager API',
  'Gemini Cloud Assist API',
  'Generative Language API',
  'Drive Labels API',
  'Drive Activity API',
  'Distance Matrix API',
  'Directions API',
  'Digital Asset Links API',
  'Dataform API',
  'Custom Search API',
  'Container Registry API',
  'Contacts API',
  'Cloud Vision API',
  'Cloud Video Intelligence API',
  'Cloud Translation API',
  'Cloud Trace API',
  'Cloud Storage API',
  'Cloud Storage',
  'Cloud SQL',
  'Cloud Speech-to-Text API',
  'Cloud Search API',
  'Cloud Run Admin API',
  'Cloud Pub/Sub API',
  'Cloud Natural Language API',
  'Cloud Monitoring API',
  'Cloud Logging API',
  'Cloud Location Finder API',
  'Cloud Identity API',
  'Cloud Datastore API',
  'Cloud Dataplex API',
  'Cloud AutoML API',
  'Cloud Asset API',
  'CalDAV API',
  'BigQuery Storage API',
  'BigQuery Reservation API',
  'BigQuery Migration API',
  'BigQuery Data Policy API',
  'BigQuery Connection API',
  'BigQuery API',
  'Artifact Registry API',
  'Apps Script API',
  'Analytics Hub API',
  'Air Quality API',
  'AI Platform Training & Prediction API',
  'Aerial View API',
  'Admin SDK API',
  'Address Validation API'
];

const apiKeys = {};
for (const name of apiNames) {
  const envName = name.toUpperCase().replace(/[^A-Z0-9]+/g, '_') + '_KEY';
  apiKeys[name] = process.env[envName] || null;
}

module.exports = { apiKeys };
